<template>
  <div id="app">
    <router-view name="header"></router-view>
    <main>
      <div class="container">
        <router-view></router-view>
      </div>
    </main>
    <router-view name="footer"></router-view>
  </div>
</template>
<script>
  export default {
    data () {
      return {
      }
    },
    created () {
      if (this.$cookies.isKey('cart')) {
        this.$store.commit('set_orderList',Vue.$cookies.get('cart'));
      }
    }
  }
</script>

<style>

*, *::before, *::after{
  margin:0;
  padding:0;
  box-sizing: border-box;
}

body {
  width: 100%;
  font-size: 18px;
  direction: rtl;
}

a {
  color: black;
  text-decoration: none;
}

a:hover {
  color: black;
  text-decoration: none;
}

ul{
  list-style: none;
}

.my-inline-block{
  display: inline-block;
}



@media screen and (max-width: 798px) and (min-width: 498px) {
  .container {
    margin: 0 2.5rem;
  }
  .product-image {
    text-align: center;
  }

}

@media screen and (max-width: 497px) {
  body {
    font-size: 12px;
  }

  .container {
    margin: 0 1.5rem;
  }
  

}


/*
my definition
*/
.color-red{
  color: red;
}

.color-green{
  color: green;
}

.display-inline-block {
  display: inline-block;
}


/* ----------------------------------------------
 * Generated by Animista on 2019-9-25 21:8:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation focus-in-expand-fwd
 * ----------------------------------------
 */
@-webkit-keyframes focus-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-800px);
            transform: translateZ(-800px);
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}
@keyframes focus-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-800px);
            transform: translateZ(-800px);
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}


/* ----------------------------------------------
 * Generated by Animista on 2019-9-25 22:6:30
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation roll-in-blurred-bottom
 * ----------------------------------------
 */
@-webkit-keyframes roll-in-blurred-bottom {
  0% {
    -webkit-transform: translateY(800px) rotate(720deg);
            transform: translateY(800px) rotate(720deg);
    -webkit-filter: blur(50px);
            filter: blur(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotate(0deg);
            transform: translateY(0) rotate(0deg);
    opacity: 1;
  }
}
@keyframes roll-in-blurred-bottom {
  0% {
    -webkit-transform: translateY(800px) rotate(720deg);
            transform: translateY(800px) rotate(720deg);
    -webkit-filter: blur(50px);
            filter: blur(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotate(0deg);
            transform: translateY(0) rotate(0deg);
    opacity: 1;
  }
}


</style>
