<template>
  <div id="app">
    <router-view name="sidebar"></router-view>
    <div id="app-child"  v-bind:class="{ 'sidebar-on': displaySidebar, 'sidebar-of': !displaySidebar }">
      <router-view name="header"></router-view>
      <main id="MainClass">
      <div class="container">
        <router-view></router-view>
      </div>
      </main>
      <router-view name="footer"></router-view>
    </div>
  </div>
</template>
<script>
  export default {
    data () {
      return {
      }
    },
    created () {
      if (this.$cookies.isKey('cart')) {
        this.$store.commit('set_orderList',Vue.$cookies.get('cart'));
      }
    },
    computed:{
      displaySidebar () {
        return this.$store.getters.getDisplaySidebar;
      }
    }
  }
</script>

<style>

*, *::before, *::after{
  margin:0;
  padding:0;
  box-sizing: border-box;
}


body {
  width: 100%;
  font-size: 18px;
  direction: rtl;
}

#app {
  display: flex;
  width: 100%;
  flex-direction: row;
  /* height: 100vh; */
}

#app-child {
  display: flex;
  flex-direction: column;
  transition: all .8s cubic-bezier(1.0, 0.5, 0.8, 1.0);
  /* height: 100vh; */
}

.sidebar-on{
  width: 85%;
  margin-right: 15%;
}

.sidebar-of{
  width: 100%;
}

#MainClass {
  flex-grow: 1;
  margin: 0 0.5rem;
}

a {
  color: black;
  text-decoration: none;
}

a:hover {
  color: black;
  text-decoration: none;
}

ul{
  list-style: none;
}

.my-inline-block{
  display: inline-block;
}

.icon-size{
  width: 0.8rem;
  height: 0.8rem;
}

.icon-size-2{
  width: 1.2rem;
  height: 1.2rem;
}

.icon-size-3{
  width: 1.8rem;
  height: 1.8rem;
}

.icon-size-4{
  width: 2.2rem;
  height: 2.2rem;
}

.icon-size-5{
  width: 3rem;
  height: 3rem;
}

.container {
  margin: 0 1.5rem;
}


.rounded {
  border-radius: 50%;
}

@media screen and (max-width: 798px) and (min-width: 498px) {
  .container {
    margin: 0 2.5rem;
  }
  .product-image {
    text-align: center;
  }

}

@media screen and (max-width: 497px) {
  body {
    font-size: 12px;
  }

  .container {
    margin: 0 1.5rem;
  }
  

}


/*
my definition
*/

.color-red{
  color: red;
}

.color-green{
  color: green;
}

.display-inline-block {
  display: inline-block;
}

.mHover-red:hover {
  filter: invert(27%) sepia(51%) saturate(2878%) hue-rotate(346deg) brightness(104%) ;
 
}

.mHover-yellow:hover {
  filter: invert(96%) sepia(15%) saturate(4759%) hue-rotate(321deg) brightness(110%) contrast(88%);
}

.one-pading-x {
  padding: 1rem;
}

.half-margin-x {
  margin: 0.3rem;
}


/* ----------------------------------------------
 * Generated by Animista on 2019-9-25 21:8:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation focus-in-expand-fwd
 * ----------------------------------------
 */
@-webkit-keyframes focus-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-800px);
            transform: translateZ(-800px);
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}
@keyframes focus-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    -webkit-transform: translateZ(-800px);
            transform: translateZ(-800px);
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    -webkit-filter: blur(0);
            filter: blur(0);
    opacity: 1;
  }
}


/* ----------------------------------------------
 * Generated by Animista on 2019-9-25 22:6:30
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation roll-in-blurred-bottom
 * ----------------------------------------
 */
@-webkit-keyframes roll-in-blurred-bottom {
  0% {
    -webkit-transform: translateY(800px) rotate(720deg);
            transform: translateY(800px) rotate(720deg);
    -webkit-filter: blur(50px);
            filter: blur(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotate(0deg);
            transform: translateY(0) rotate(0deg);
    opacity: 1;
  }
}
@keyframes roll-in-blurred-bottom {
  0% {
    -webkit-transform: translateY(800px) rotate(720deg);
            transform: translateY(800px) rotate(720deg);
    -webkit-filter: blur(50px);
            filter: blur(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0) rotate(0deg);
            transform: translateY(0) rotate(0deg);
    opacity: 1;
  }
}

.slide-fade-enter-active {
  transition: all .3s ease;
}
.slide-fade-leave-active {
  transition: all .8s cubic-bezier(1.0, 0.5, 0.8, 1.0);
}
.slide-fade-enter, .slide-fade-leave-to
/* .slide-fade-leave-active below version 2.1.8 */ {
  transform: translateX(10px);
  opacity: 0;
}

</style>
